# Generated by Django 5.2.17 on 2026-09-25 00:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_name', models.CharField(max_length=100)),
                ('event_source', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('AwsApiCall', 'AwsApiCall'), ('AwsConsoleSignIn', 'AwsConsoleSignIn')], default='AwsApiCall', max_length=30)),
                ('read_only', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='IAMUser', max_length=30)),
                ('source_ip', models.GenericIPAddressField()),
                ('aws_region', models.CharField(default='us-east-1', max_length=30)),
                ('user_agent', models.CharField(default='console.amazonaws.com', max_length=200)),
                ('request_parameters', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('prev_hash', models.CharField(editable=False, max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-event_time', '-id'],
            },
        ),
    ]
